stages:
  - build
  - test
  - deploy

variables:
  DOCKER_HOST: "tcp://localhost:2375"

build:
  stage: build
  image: docker:18.09
  services:
    - docker:18.09-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker info
    - docker build -f Dockerfile --tag $CI_REGISTRY_IMAGE:${CI_COMMIT_SHORT_SHA} .
    - docker push $CI_REGISTRY_IMAGE:${CI_COMMIT_SHORT_SHA}

test:
  stage: test
  image: docker:18.09
  services:
    - docker:18.09-dind
  script:
    - apk add curl
    - docker run -d --name tester -p 8000:80 $CI_REGISTRY_IMAGE:${CI_COMMIT_SHORT_SHA} 
    - CONTAINER_IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAdresss}}{{end}}' tester)
    - sleep 15
    - curl $CONTAINER_IP:8000
    - docker rm -f tester

deploy:
  stage: deploy
  image: alpine/helm:3.5.4
  script:
    - helm upgrade website-helm-k8s-cicd ./deploy --install --set-string image.tag=${CI_COMMIT_SHORT_SHA} --namespace website-helm-k8s-cicd --create-namespace --timeout 5m0s
