stages:
  - build
  - deploy
variables:
  DOCKER_HOST: "tcp://localhost:2375"

build:
  stage: build
  image: docker:19.03.12
  services:
    - docker:19.03.12-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker info
    - docker run -d nginx
    - docker build -f Dockerfile --tag $CI_REGISTRY_IMAGE:${CI_COMMIT_SHORT_SHA} .
    - docker push $CI_REGISTRY_IMAGE:${CI_COMMIT_SHORT_SHA}

deploy:
  stage: deploy
  image: alpine/helm:3.5.4
  script:
    - helm upgrade website-helm-k8s-cicd ./deploy --install --set-string image.tag=${CI_COMMIT_SHORT_SHA} --namespace website-helm-k8s-cicd --timeout 5m0s
