stages:
  - build
  - deploy

variables:
  IMAGE_NAME: mkingst-gitlab.ddns.net:5050/mkingst/website-helm-k8s-cicd
  DOCKER_HOST: https://mkingst-gitlab.ddns.net:5050

build:
  stage: build
  image: docker:18-git
  services:
    - docker:18-dind
  script:
    - docker login -u mkingst -p $CI_JOB_TOKEN $DOCKER_HOST
    - docker build -f Dockerfile --tag ${IMAGE_NAME}:${CI_COMMIT_SHORT_SHA} .
    - docker push ${IMAGE_NAME}:${CI_COMMIT_SHORT_SHA}

deploy:
  stage: deploy
  image: alpine/helm:3.5.4
  script:
    - helm upgrade website-helm-k8s-cicd ./deploy --install --set-string image.tag=${CI_COMMIT_SHORT_SHA} --namespace website-helm-k8s-cicd --timeout 5m0s
