apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.application.name }}
  namespace: {{ .Values.application.name }}
spec:
  ingressClassName: nginx
  rules:
    - host: micheal.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.application.name }}
                port:
                  number: 80
